"""Initial migration

Revision ID: 07ac7ef563cb
Revises: 
Create Date: 2022-08-18 23:11:39.780207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ac7ef563cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('manager', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product', 'module', 'manager', name='unique_group')
    )
    op.create_table('gitlab_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('web_url', sa.String(length=128), nullable=False),
    sa.Column('gitlab_group_id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gitlab_group_id'], ['gitlab_group.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_group_id'], ['hierarchy_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonar_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('sonar_id', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gitlab_project_id'], ['gitlab_project.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_group_id'], ['hierarchy_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gitlab_project_id'),
    sa.UniqueConstraint('sonar_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sonar_project')
    op.drop_table('gitlab_project')
    op.drop_table('hierarchy_group')
    op.drop_table('gitlab_group')
    # ### end Alembic commands ###
